request : 
    host : "fakestoreapi.com"
    path : "products"

dbcall : 
    host : "0.0.0.0"
    port : "8083"
    basepath : "api"
    path : "creatingRecorddb"
    
sfcall : 
  #host : "syn-products-integration-sf-zr9fp9.5sc6y6-3.usa-e2.cloudhub.io"
  host : "0.0.0.0"
  port : "8084"    
  basepath : "api" 
  path : "creatingRecorssf" 

smtp :
  host : "smtp.gmail.com"
  user :  "gopivarri1@gmail.com"
  password : "guumxdpfqjooatoo"
  port : "587"

http :
  host : "0.0.0.0"
  port : "8082"
  
  