request : 
    host : "fakestoreapi.com"
    path : "products"

dbcall : 
    host : "0.0.0.0"
    port : "8083"
    basepath : "api"
    path : "insert/db"
    
sfcall : 
  #host : "syn-products-integration-sf-zr9fp9.5sc6y6-3.usa-e2.cloudhub.io"
  host : "0.0.0.0"
  port : "8084"    
  basepath : "api" 
  path : "insert/sf" 

mail:
  #host : "sync-products-integration-mail-sapi-zr9fp9.5sc6y6-2.usa-e2.cloudhub.io"
  host : "0.0.0.0"
  port : "8085"
  basepath : "api"
  path : "sendmail" 

http :
  host : "0.0.0.0"
  port : "8081"
  
  